import { test, expect } from "@playwright/test";

/**
 * Composer (post a card) E2E tests.
 *
 * Auth setup: Clerk does not support headless sign-in without its test SDK.
 * Tests that require a signed-in session are marked with the "auth" tag and
 * will be skipped unless a pre-built auth state is available at
 * tests/e2e/.auth/user.json (generated by running `npm run test:e2e:setup`).
 *
 * Auth-free tests cover the unauthenticated state and UI structure.
 */

// ---------------------------------------------------------------------------
// Without auth — public UI
// ---------------------------------------------------------------------------

test.describe("Composer trigger (unauthenticated)", () => {
  test("Post an ad button is visible on the wall", async ({ page }) => {
    await page.goto("/us");
    // The compose button is always visible.
    const postBtn = page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first();
    await expect(postBtn).toBeVisible({ timeout: 10_000 });
  });

  test("Clicking Post an ad while signed out prompts Clerk sign-in", async ({ page }) => {
    await page.goto("/us");
    const postBtn = page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first();
    await postBtn.click();
    // Either the Clerk modal appears or we're redirected to a sign-in page.
    const clerkModal = page.locator(".cl-modal-backdrop, .cl-rootBox, [data-testid='modal']");
    const signInPage = page.locator("form:has(input[name='identifier'])");
    await expect(clerkModal.or(signInPage)).toBeVisible({ timeout: 8_000 });
  });
});

// ---------------------------------------------------------------------------
// Composer step structure — requires auth
// ---------------------------------------------------------------------------

test.describe("Composer steps @auth", () => {
  test.use({ storageState: "tests/e2e/.auth/user.json" });

  test("Step 1 Design: shows card style options", async ({ page }) => {
    await page.goto("/us");
    await page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first().click();

    // Composer opens.
    await expect(page.locator(".composer")).toBeVisible({ timeout: 8_000 });
    // Step 1 label.
    await expect(page.locator(".composer header span")).toContainText("Design");
    // Style options grid.
    await expect(page.locator(".style-options")).toBeVisible();
  });

  test("Step 1: selecting a theme updates the live preview", async ({ page }) => {
    await page.goto("/us");
    await page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first().click();
    await expect(page.locator(".composer")).toBeVisible({ timeout: 8_000 });

    // Click the "Dark" theme option.
    await page.locator(".style-dark").click();
    await expect(page.locator(".preview-canvas .wall-card")).toHaveClass(/theme-dark/);
  });

  test("Step 1 → Step 2: advancing shows the details form", async ({ page }) => {
    await page.goto("/us");
    await page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first().click();
    await expect(page.locator(".composer")).toBeVisible({ timeout: 8_000 });

    await page.locator(".composer footer button[type='submit']").click();
    await expect(page.locator(".composer header span")).toContainText("Details");
    await expect(page.locator("input[name='name']")).toBeVisible();
  });

  test("Step 2: validation fires when required fields are empty", async ({ page }) => {
    await page.goto("/us");
    await page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first().click();
    await expect(page.locator(".composer")).toBeVisible({ timeout: 8_000 });

    // Skip to step 2.
    await page.locator(".composer footer button[type='submit']").click();
    await expect(page.locator("input[name='name']")).toBeVisible();

    // Try to advance without filling anything.
    await page.locator(".composer footer button[type='submit']").click();
    // Validation summary or native validity message should appear.
    const errorVisible =
      await page.locator(".validation-summary, .field-error").isVisible() ||
      await page.locator("input:invalid, textarea:invalid").count() > 0;
    expect(errorVisible).toBe(true);
  });

  test("Step 2 → Step 3: valid form advances to duration step", async ({ page }) => {
    await page.goto("/us");
    await page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first().click();
    await expect(page.locator(".composer")).toBeVisible({ timeout: 8_000 });

    // Step 1 → Step 2.
    await page.locator(".composer footer button[type='submit']").click();
    await expect(page.locator("input[name='name']")).toBeVisible();

    // Fill required fields.
    await page.fill("input[name='name']", "Test Plumber Co");
    await page.selectOption("select[name='category'], select >> nth=0", { label: "Services" });
    await page.selectOption("select[name='subcategory'], select >> nth=1", { index: 1 });
    await page.fill("textarea[name='line']", "Professional plumbing services");
    await page.fill("input[name='phone']", "+1 555 123 4567");

    // Step 2 → Step 3.
    await page.locator(".composer footer button[type='submit']").click();
    // Moderation check may take a moment.
    await expect(page.locator(".composer header span")).toContainText("Duration", { timeout: 15_000 });
  });

  test("Step 3: duration options are shown", async ({ page }) => {
    await page.goto("/us");
    await page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first().click();
    await expect(page.locator(".composer")).toBeVisible({ timeout: 8_000 });

    await page.locator(".composer footer button[type='submit']").click();
    await page.fill("input[name='name']", "Test Plumber Co");
    await page.selectOption("select >> nth=0", { label: "Services" });
    await page.selectOption("select >> nth=1", { index: 1 });
    await page.fill("textarea[name='line']", "Professional plumbing services");
    await page.fill("input[name='phone']", "+1 555 123 4567");
    await page.locator(".composer footer button[type='submit']").click();
    await expect(page.locator(".payment-options")).toBeVisible({ timeout: 15_000 });
    // Four duration options.
    await expect(page.locator(".payment-option")).toHaveCount(4);
  });

  test("draft banner appears on reopening the composer with saved content", async ({ page }) => {
    await page.goto("/us");
    await page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first().click();
    await expect(page.locator(".composer")).toBeVisible({ timeout: 8_000 });

    // Step 2 and fill name.
    await page.locator(".composer footer button[type='submit']").click();
    await page.fill("input[name='name']", "My Draft Business");
    // Wait for autosave debounce.
    await page.waitForTimeout(400);

    // Close composer.
    await page.locator(".composer header button[aria-label='Close']").click();
    await expect(page.locator(".composer")).not.toBeVisible();

    // Reopen.
    await page.locator(".compose-btn, button:has-text('Post'), [aria-label*='Post']").first().click();
    await expect(page.locator(".composer-draft-banner")).toBeVisible({ timeout: 5_000 });
  });
});
